### ISSUE TITLE
Get the Gold class schedule data in a machine readable form

### ISSUE THREAD

**Issue by ydaiydai** [ucsb-cs48-w19/4pm-gold-scheduler#10]
Capture it in some format that we can read it in our Java code

- [ ] Write scraper
- [ ] Get the data 
- [ ] Organize the data in some format
- [ ] Write codes that read the data in to the Gold Scheduler Web

**Comment by elizamr** [comment]
Mentor Approved

- Consider breaking this issue into smaller pieces - for instance, writing the scraper can be its own issue, and displaying all collected data can be another issue.
