### ISSUE TITLE
Have ways to show class conflicts

### ISSUE THREAD

**Issue by ydaiydai** [ucsb-cs48-w19/4pm-gold-scheduler#12]
To have the checking, also certain display of (potential) class conflicts

- [ ] be able to compare time for class conflict
- [ ] display on the schedule for class conflicts (red color and warning?)
- [ ] can also show potential class conflict before putting in the schedule (warning)

**Comment by elizamr** [comment]
Mentor Approved
- You may want to focus on notifying the user of immediate conflicts first (one issue), then design an appropriate UI second (separate issue).
