### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by K1n9sley** [ucsb-cs48-w19/4pm-gold-scheduler#25]
- [x] Write sample HTML for Gold Scheduler web app

**Comment by elizamr** [comment]
Mentor Approved
- Consider combining this issue with #26 since they're heavily related.

**Comment by yuchenbi** [comment]
I am current working on the weekly schedule table.

**Comment by yuchenbi** [comment]
https://github.com/yuchenbi/4pm-gold-scheduler
