### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by K1n9sley** [ucsb-cs48-w19/4pm-gold-scheduler#26]
- [x] Make a sample css for Gold Scheduler.

**Comment by elizamr** [comment]
Mentor Approved

**Comment by yuanxuecs** [comment]
- [ ] sample data create
- [ ] create botton for the quarter choosing
- [ ] create drop-down list of class
- [ ] send requires to back part
- [ ] read requires from back part
- [ ] insert to schedule 
- [ ] conflict processing
