### ISSUE TITLE
Front-end

### ISSUE THREAD

**Issue by K1n9sley** [ucsb-cs48-w19/4pm-gold-scheduler#27]
- [ ] Make a sample front-end for Gold Scheduler (display class info and weekly schedule on web)

**Comment by elizamr** [comment]
Mentor Approved

**Comment by ydaiydai** [comment]
Working on functions in flask connected to frontend

**Comment by ydaiydai** [comment]
updated the initial web page, working on linking to the next page which would be the class schedule list based on the subject the user chose.
