### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by K1n9sley** [ucsb-cs48-w19/4pm-gold-scheduler#29]
- [x] Set up data base and manage small amount of class data

**Comment by elizamr** [comment]
Mentor Approved
- #20 has the same name as this issue - and #30 appears to be a part of this issue. Consider combining issues or revising previous ones.

**Comment by YanwuTong** [comment]
build a model that have one list contain all class type such as "CMPSC" and under each class type. we have a sublist that contain all courses under this type such as under type "CMPSC" we have "CMPSC 8" and "CMPSC 16". under each courses, we can get the specific information for this course includes class time, professor, class code and etc.

**Comment by YanwuTong** [comment]
just upload the README.md, try to put other things on
https://github.com/YanwuTong/4pm-gold-scheduler.git

**Comment by YanwuTong** [comment]
need to change branch

**Comment by YanwuTong** [comment]
add sample version of course list under db branch, the sturcture can be used
