### ISSUE TITLE
- [x] sample data create

### ISSUE THREAD

**Issue by yuanxuecs** [ucsb-cs48-w19/4pm-gold-scheduler#36]
- [x] sample data create
- [x] create botton for the quarter choosing
- [x] create drop-down list of class
- [ ] send requires to back part
- [ ] read requires from back part
- [ ] insert to schedule 
- [ ] conflict processing
https://github.com/ucsb-cs48-w19/4pm-gold-scheduler/blob/yuchenbi-yuanxue-hello-world3/gold.html
_Originally posted by @yuanxuecs in https://github.com/ucsb-cs48-w19/4pm-gold-scheduler/issues/26#issuecomment-461662427_

**Comment by elizamr** [comment]
Mentor Approved
